# Generated by Copilot
# Backend configuration - uncomment and configure when ready

# terraform {
#   backend "s3" {
#     bucket         = "your-terraform-state-bucket"
#     key            = "ep-tracker/terraform.tfstate"
#     region         = "us-east-1"
#     encrypt        = true
#     dynamodb_table = "terraform-lock"
#   }
# }
