# Generated by Copilot
# Variables for the Terraform configuration

variable "repository_url" {
  description = "The URL of your code repository (GitHub, CodeCommit, etc.)"
  type        = string
}

variable "aws_region" {
  description = "The AWS region to deploy resources in"
  type        = string
  default     = "us-east-1"
}

variable "branch_name" {
  description = "The branch name to deploy from"
  type        = string
  default     = "main"
}
